In [1]:
import sys
sys.path.append('..')

In [48]:
from model import *
from utils import *
import copy

In [3]:
model = build_networks('resnet20', 10, (32,32,3))

Instructions for updating:
Colocations handled automatically by placer.


In [11]:
x_train, x_test, y_train, y_test = load_dataset('cifar10', shuffle=False)
print("x_train shape: {}".format(x_train.shape))
print("y_train shape: {}".format(y_train.shape))
x_train_val, x_val, y_train_val, y_val = split_validation_dataset(x_train, y_train)

x_train shape: (50000, 32, 32, 3)
y_train shape: (50000, 10)


In [13]:
ret = model.predict(x_train)

In [15]:
ret.shape

(50000, 10)

In [16]:
y_train.shape

(50000, 10)

In [17]:
ret = np.argmax(ret, axis=1)

In [18]:
ret.shape

(50000,)

In [19]:
ret

array([8, 8, 8, ..., 8, 8, 8], dtype=int64)

In [20]:
y_label = np.argmax(y_train, axis=1)

In [21]:
y_label

array([6, 9, 9, ..., 9, 1, 1], dtype=int64)

In [22]:
q = ret == y_label

In [23]:
q.shape

(50000,)

In [25]:
np.sum(q)

5000

In [31]:
p = np.array(q, dtype=np.int)

In [33]:
np.sum(p)

5000

In [35]:
p2 = p

In [37]:
p2[0] = 1

In [38]:
p2

array([1, 0, 0, ..., 0, 0, 0])

In [39]:
p2.shape

(50000,)

In [41]:
p3 = p + p2

In [43]:
np.sum(p3)

10002

In [58]:
np.sum(p)

5001

In [59]:
p2 = copy.deepcopy(p)
p2[1] = 1

In [60]:
p2

array([1, 1, 0, ..., 0, 0, 0])

In [61]:
np.sum(p2)

5002

In [62]:
p3 = p + p2
p3[p3>0] = 1

In [63]:
np.sum(p3)

5002

In [64]:
p3.shape

(50000,)