In [1]:
from model import *
from utils import *
from settings import *

Using TensorFlow backend.


In [2]:
x_train, x_test, y_train, y_test = load_dataset('cifar10')

In [3]:
import numpy as np

In [4]:
x = np.ones(20)

In [5]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [6]:
x.shape

(20,)

In [7]:
y = np.zeros(20)

In [8]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [10]:
x = [i for i in range(20)]

In [11]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [12]:
np.array(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])