In [1]:
from model import *
from utils import *
from settings import *

Using TensorFlow backend.


In [2]:
x_train, x_test, y_train, y_test = load_dataset('cifar10')

In [3]:
import numpy as np

In [4]:
x = np.ones(20)

In [5]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [6]:
x.shape

(20,)

In [7]:
y = np.zeros(20)

In [8]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [10]:
x = [i for i in range(20)]

In [11]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [12]:
np.array(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.sum(x)

190

In [14]:
x = np.array([0,1,1,0,0,1])
y = np.array([1,2,3,4,5,6])

In [15]:
np.nonzero(x)

(array([1, 2, 5], dtype=int64),)

In [16]:
y[np.nonzero(x)]

array([2, 3, 6])

In [17]:
x = np.array([0,1,0,0,0,1,0,0,0,1,0,0,1,1,1,0,0,0,0,1])

In [18]:
len(x)

20

In [19]:
np.nonzero(x)

(array([ 1,  5,  9, 12, 13, 14, 19], dtype=int64),)

In [20]:
input_size = (32, 32, 3)
model = build_networks('densenet', num_classes=10, input_size=input_size)

Instructions for updating:
Colocations handled automatically by placer.


In [22]:
ret = model.get_weights()

In [24]:
type(ret[0])

numpy.ndarray

In [25]:
x

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1])

In [28]:
2 in x

False

In [ ]:
ty